### ISSUE TITLE
Issue with WP Contact Form 7 (Submits on Arrow Press)

### ISSUE THREAD

**Issue by jackmcdowell** [mayakokits/jquery.fancyspinbox#1]
I have a website where I am trying to implement this plugin but each time I click on an arrow, the Contact form 7 form tries to submit itself. See https://expressoregonatms.com/demo-contact/
Any ideas?

**Comment by mayakokits** [comment]
oh, obviously I forgot the type attribute on the buttons. please add `type="button"` to both the `.spin-up` and the `.spin-down` button. I'll fix it later when I heave time.

**Comment by mayakokits** [comment]
ok, fixed :-)

**Comment by jackmcdowell** [comment]
Thank you Maya! It's a great script :)
